shopflow:
  target: dev
  outputs:
    dev:
      catalog: shopflow
      host: dbc
      http_path: /sql/1.0/
      schema: bronze
      threads: 1
      token: dapi
      type: databricks
